services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - .:/app
      - /app/node_modules

    container_name: backend-mid-wispok
    image: wispok-test
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongodb/mongodb-community-server:7.0-ubi8
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db 
    restart: always
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ping: 1})"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data: